server:
  port: 8080

spring:
  application:
    name: order

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true